services:
  - type: web
    name: fastapi-app
    env: docker
    region: frankfurt
    plan: free
    healthCheckPath: /docs
    envVars:
      - key: POSTGRES_USER
        sync: false
      - key: POSTGRES_PASSWORD
        sync: false
      - key: POSTGRES_DB
        sync: false
      - key: POSTGRES_SERVER
        sync: false
      - key: POSTGRES_PORT
        value: 5432
